services:

    database:
        image: postgres
        ports:
            - 5432:5432
        restart: always
        
        environment:
            POSTGRES_USER: osm
            POSTGRES_PASSWORD: osm
            POSTGRES_DB: osm
